-- Migration Phase 27 — Différenciateurs Sprint 6
-- D1: Contexte business sur clients (AI scoring contextualisé)
ALTER TABLE clients ADD COLUMN business_type TEXT DEFAULT 'B2B générique';
ALTER TABLE clients ADD COLUMN brand_voice TEXT DEFAULT 'Professionnel, rassurant et québécois naturel.';
ALTER TABLE clients ADD COLUMN scoring_prompt_extra TEXT DEFAULT '';

-- D3: Géolocalisation sur leads (Mapbox)
ALTER TABLE clients ADD COLUMN mapbox_token TEXT DEFAULT '';
ALTER TABLE leads ADD COLUMN lat REAL;
ALTER TABLE leads ADD COLUMN lng REAL;
ALTER TABLE leads ADD COLUMN address TEXT DEFAULT '';

-- D5: Tokens signature
CREATE TABLE IF NOT EXISTS signing_tokens (
  id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL,
  lead_id TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TEXT NOT NULL,
  signed_at TEXT,
  signed_pdf_key TEXT,
  signer_ip TEXT,
  signer_ua TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- D4: Dashboard layouts
CREATE TABLE IF NOT EXISTS dashboard_layouts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  client_id TEXT,
  name TEXT NOT NULL DEFAULT 'Mon dashboard',
  layout_json TEXT NOT NULL DEFAULT '[]',
  is_default INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- D7: Packs industrie
CREATE TABLE IF NOT EXISTS industry_packs (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  icon TEXT DEFAULT '📦',
  industries TEXT DEFAULT '',
  snapshot_json TEXT NOT NULL DEFAULT '{}',
  is_published INTEGER DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Seed 5 packs industrie
INSERT OR IGNORE INTO industry_packs (id, slug, name, description, icon, industries, snapshot_json) VALUES
('pack-generic-b2b', 'generic-b2b', 'Generic B2B', 'Pack universel pour toute PME B2B québécoise', '🏢', 'B2B,Services,Conseil', '{"custom_fields":[{"name":"Budget annuel","key":"budget_annuel","type":"currency"},{"name":"Taille entreprise","key":"taille_entreprise","type":"select","options":["1-10","11-50","51-200","200+"]},{"name":"Secteur","key":"secteur","type":"text"},{"name":"Décideur","key":"decideur","type":"text"}],"workflows":[{"name":"Bienvenue nouveau lead","trigger":"lead.created","steps":[{"type":"wait","delay_hours":1},{"type":"email","subject":"Bienvenue chez nous!","body":"Bonjour {{lead.name}}, merci de votre intérêt."}]},{"name":"Relance 7 jours","trigger":"lead.created","steps":[{"type":"wait","delay_hours":168},{"type":"sms","body":"Bonjour {{lead.name}}, avez-vous eu le temps de réfléchir?"}]}],"templates":[{"name":"Bienvenue","channel":"email","subject":"Bienvenue {{lead.name}}!","body":"Bonjour {{lead.name}},\n\nMerci de nous avoir contactés. Nous sommes ravis de vous compter parmi nos prospects.\n\nCordialement,\n{{client.name}}"},{"name":"Relance douce","channel":"sms","body":"Bonjour {{lead.name}}, avez-vous des questions? On est disponibles 😊"}],"smart_lists":[{"name":"Leads chauds","filters":{"min_score":70}},{"name":"Sans activité 7j","filters":{"inactive_days":7}},{"name":"Deals actifs","filters":{"status":"qualified"}}]}'),
('pack-real-estate', 'real-estate-pro-qc', 'Real Estate Pro QC', 'Optimisé pour les courtiers immobiliers québécois (OACIQ, AMF)', '🏡', 'Immobilier,Courtier,Real Estate', '{"custom_fields":[{"name":"Type projet","key":"type_projet","type":"select","options":["Achat","Vente","Investissement","Refinancement"]},{"name":"Budget","key":"budget","type":"currency"},{"name":"Délai","key":"delai","type":"select","options":["Immédiat","1-3 mois","3-6 mois","6+ mois"]},{"name":"Quartier ciblé","key":"quartier","type":"text"},{"name":"Propriétés visitées","key":"nb_visites","type":"number"},{"name":"Pré-approuvé","key":"pre_approuve","type":"checkbox"}],"workflows":[{"name":"Nouveau lead acheteur","trigger":"lead.created","steps":[{"type":"wait","delay_hours":0.5},{"type":"email","subject":"Bienvenue dans votre recherche immobilière","body":"Bonjour {{lead.name}}, je suis {{client.name}} et je suis là pour vous aider à trouver votre propriété idéale."}]},{"name":"Relance 3 jours","trigger":"lead.created","steps":[{"type":"wait","delay_hours":72},{"type":"sms","body":"Bonjour {{lead.name}}, de nouvelles propriétés correspondent à vos critères. Souhaitez-vous les visiter?"}]},{"name":"Rappel mandat expirant","trigger":"lead.tag_added","steps":[{"type":"email","subject":"Votre mandat arrive à échéance","body":"Bonjour {{lead.name}}, votre mandat expire dans 30 jours. Souhaitez-vous le renouveler?"}]}],"templates":[{"name":"Confirmation visite","channel":"email","subject":"Confirmation de visite — {{lead.name}}","body":"Bonjour {{lead.name}},\n\nJe confirme notre visite de propriété.\n\nN''hésitez pas à me contacter si vous avez des questions.\n\n{{client.name}} | Courtier immobilier"},{"name":"Offre reçue","channel":"sms","body":"Bonne nouvelle {{lead.name}}! Une offre a été soumise sur votre propriété. Je vous appelle dans les prochaines minutes."},{"name":"Disclaimer AMF","channel":"email","subject":"Information importante — Courtage immobilier","body":"Conformément à la Loi sur le courtage immobilier (RLRQ c. C-73.2), veuillez noter que {{client.name}} est titulaire d''un certificat délivré par l''OACIQ."}],"smart_lists":[{"name":"Acheteurs pré-approuvés","filters":{"custom_field_pre_approuve":true}},{"name":"Vendeurs actifs","filters":{"custom_field_type_projet":"Vente"}},{"name":"Leads sans visite","filters":{"custom_field_nb_visites":0}}]}'),
('pack-local-services', 'local-services', 'Services Locaux', 'Nettoyage, plomberie, électricien, rénovation', '🔧', 'Nettoyage,Plomberie,Électricité,Rénovation', '{"custom_fields":[{"name":"Type service","key":"type_service","type":"select","options":["Nettoyage résidentiel","Nettoyage commercial","Plomberie","Électricité","Rénovation","Déménagement"]},{"name":"Surface (pi²)","key":"surface","type":"number"},{"name":"Fréquence","key":"frequence","type":"select","options":["Unique","Hebdomadaire","Bi-mensuel","Mensuel"]},{"name":"Date souhaitée","key":"date_service","type":"date"}],"workflows":[{"name":"Confirmation réservation","trigger":"appointment.booked","steps":[{"type":"sms","body":"Bonjour {{lead.name}}, votre rendez-vous est confirmé. À bientôt!"}]},{"name":"Rappel veille","trigger":"appointment.booked","steps":[{"type":"wait","delay_hours":20},{"type":"sms","body":"Rappel: votre service est demain! Des questions? Répondez à ce SMS."}]},{"name":"Suivi satisfaction","trigger":"appointment.completed","steps":[{"type":"wait","delay_hours":4},{"type":"sms","body":"Bonjour {{lead.name}}, j''espère que vous êtes satisfait(e) de notre service. Un avis Google nous aiderait beaucoup! 🙏"}]}],"templates":[{"name":"Devis envoyé","channel":"email","subject":"Votre devis personnalisé","body":"Bonjour {{lead.name}},\n\nSuite à votre demande, veuillez trouver ci-joint votre devis.\n\nN''hésitez pas à nous contacter pour toute question.\n\n{{client.name}}"},{"name":"Confirmation SMS","channel":"sms","body":"✅ Réservation confirmée! On vous voit le {{appointment.date}} à {{appointment.time}}. {{client.name}}"}],"smart_lists":[{"name":"Clients récurrents","filters":{"status":"customer","min_appointments":2}},{"name":"À relancer","filters":{"inactive_days":30,"status":"customer"}}]}'),
('pack-health-wellness', 'health-wellness', 'Santé & Mieux-être', 'Dentiste, chiropracteur, massothérapie, physiothérapie', '🦷', 'Dentisterie,Chiropractie,Massage,Physiothérapie,Santé', '{"custom_fields":[{"name":"Spécialité","key":"specialite","type":"select","options":["Soins généraux","Blanchiment","Implants","Orthodontie","Urgence"]},{"name":"Assurance","key":"assurance","type":"text"},{"name":"Dernier traitement","key":"dernier_traitement","type":"date"},{"name":"Rappel nécessaire","key":"rappel_necessaire","type":"checkbox"},{"name":"Numéro dossier","key":"no_dossier","type":"text"},{"name":"Médecin référent","key":"medecin_referent","type":"text"}],"workflows":[{"name":"Rappel contrôle 6 mois","trigger":"appointment.completed","steps":[{"type":"wait","delay_hours":4320},{"type":"sms","body":"Bonjour {{lead.name}}, il est temps pour votre contrôle semestriel! Cliquez pour prendre rendez-vous."}]},{"name":"Confirmation RDV","trigger":"appointment.booked","steps":[{"type":"email","subject":"Confirmation de votre rendez-vous","body":"Bonjour {{lead.name}},\n\nVotre rendez-vous est confirmé.\n\nÀ bientôt!\n{{client.name}}"}]},{"name":"Rappel 48h","trigger":"appointment.booked","steps":[{"type":"wait","delay_hours":-48},{"type":"sms","body":"Rappel: votre RDV chez {{client.name}} est dans 48h. Pour annuler: répondez ANNULER"}]},{"name":"Suivi post-traitement","trigger":"appointment.completed","steps":[{"type":"wait","delay_hours":24},{"type":"sms","body":"Bonjour {{lead.name}}, comment vous sentez-vous après votre traitement? N''hésitez pas à nous appeler si nécessaire."}]}],"templates":[{"name":"Instructions post-soin","channel":"email","subject":"Instructions suite à votre traitement","body":"Bonjour {{lead.name}},\n\nSuite à votre traitement d''aujourd''hui, voici quelques recommandations importantes:\n\n- Évitez les aliments durs pendant 24h\n- Prenez les médicaments prescrits\n- Appelez-nous si vous ressentez une douleur inhabituellement forte\n\n{{client.name}}"},{"name":"Demande avis","channel":"sms","body":"Bonjour {{lead.name}}, merci de votre visite! Un avis Google nous aide à aider plus de patients. Merci 🙏"}],"smart_lists">[{"name":"Rappels à envoyer","filters":{"custom_field_rappel_necessaire":true}},{"name":"Sans RDV 6 mois","filters":{"inactive_days":180}},{"name":"Nouveaux patients","filters":{"status":"new"}}]}'),
('pack-coaching', 'coaching-consulting', 'Coaching & Conseil', 'Coach, consultant, formateur, mentor', '🎯', 'Coaching,Consulting,Formation,Mentorat', '{"custom_fields":[{"name":"Objectif principal","key":"objectif","type":"text"},{"name":"Revenu actuel","key":"revenu_actuel","type":"select","options":["0-50K","50K-100K","100K-250K","250K+"]},{"name":"Programme","key":"programme","type":"select","options":["Découverte","Starter","Premium","VIP","Masterclass"]},{"name":"Séances complétées","key":"seances","type":"number"},{"name":"MRR cible","key":"mrr_cible","type":"currency"}],"workflows":[{"name":"Onboarding nouveau client","trigger":"lead.status_changed_to_won","steps":[{"type":"email","subject":"Bienvenue dans le programme!","body":"Bonjour {{lead.name}},\n\nJe suis ravi(e) de vous accueillir! Voici les prochaines étapes..."}]},{"name":"Suivi hebdomadaire","trigger":"appointment.completed","steps":[{"type":"wait","delay_hours":168},{"type":"email","subject":"Suivi de la semaine","body":"Bonjour {{lead.name}},\n\nComment progressez-vous vers vos objectifs cette semaine?"}]},{"name":"Relance inactif","trigger":"lead.inactivity","steps":[{"type":"sms","body":"Bonjour {{lead.name}}, vous nous manquez! Prenons 15 min pour faire le point?"}]}],"templates":[{"name":"Invitation session découverte","channel":"email","subject":"Invitation — Session découverte offerte","body":"Bonjour {{lead.name}},\n\nJe vous invite à une session découverte de 30 minutes, offerte et sans engagement.\n\nRéservez votre place: [LIEN CALENDLY]\n\n{{client.name}}"},{"name":"Récap séance","channel":"email","subject":"Récapitulatif de notre séance","body":"Bonjour {{lead.name}},\n\nVoici les points clés de notre séance:\n\n[POINTS CLÉS]\n\nObjectifs pour la prochaine semaine:\n[OBJECTIFS]\n\nÀ bientôt!\n{{client.name}}"}],"smart_lists":[{"name":"Clients Premium+","filters":{"custom_field_programme":["Premium","VIP"]}},{"name":"Séances en retard","filters":{"custom_field_seances":0,"status":"customer"}},{"name":"À convertir","filters":{"status":"qualified","min_score":60}}]}');
